/**
 * Constants pour l'enrichissement des données INSEE
 */

// Correspondances des départements aux régions
export const DEPARTMENT_TO_REGION = {
  "01": { name: "Auvergne-Rhône-Alpes", code: "84" },
  "02": { name: "Hauts-de-France", code: "32" },
  "03": { name: "Auvergne-Rhône-Alpes", code: "84" },
  "04": { name: "Provence-Alpes-Côte d'Azur", code: "93" },
  "05": { name: "Provence-Alpes-Côte d'Azur", code: "93" },
  "06": { name: "Provence-Alpes-Côte d'Azur", code: "93" },
  "07": { name: "Auvergne-Rhône-Alpes", code: "84" },
  "08": { name: "Grand Est", code: "44" },
  "09": { name: "Occitanie", code: "76" },
  "10": { name: "Grand Est", code: "44" },
  "11": { name: "Occitanie", code: "76" },
  "12": { name: "Occitanie", code: "76" },
  "13": { name: "Provence-Alpes-Côte d'Azur", code: "93" },
  "14": { name: "Normandie", code: "28" },
  "15": { name: "Auvergne-Rhône-Alpes", code: "84" },
  "16": { name: "Nouvelle-Aquitaine", code: "75" },
  "17": { name: "Nouvelle-Aquitaine", code: "75" },
  "18": { name: "Centre-Val de Loire", code: "24" },
  "19": { name: "Nouvelle-Aquitaine", code: "75" },
  "21": { name: "Bourgogne-Franche-Comté", code: "27" },
  "22": { name: "Bretagne", code: "53" },
  "23": { name: "Nouvelle-Aquitaine", code: "75" },
  "24": { name: "Nouvelle-Aquitaine", code: "75" },
  "25": { name: "Bourgogne-Franche-Comté", code: "27" },
  "26": { name: "Auvergne-Rhône-Alpes", code: "84" },
  "27": { name: "Normandie", code: "28" },
  "28": { name: "Centre-Val de Loire", code: "24" },
  "29": { name: "Bretagne", code: "53" },
  "2A": { name: "Corse", code: "94" },
  "2B": { name: "Corse", code: "94" },
  "30": { name: "Occitanie", code: "76" },
  "31": { name: "Occitanie", code: "76" },
  "32": { name: "Occitanie", code: "76" },
  "33": { name: "Nouvelle-Aquitaine", code: "75" },
  "34": { name: "Occitanie", code: "76" },
  "35": { name: "Bretagne", code: "53" },
  "36": { name: "Centre-Val de Loire", code: "24" },
  "37": { name: "Centre-Val de Loire", code: "24" },
  "38": { name: "Auvergne-Rhône-Alpes", code: "84" },
  "39": { name: "Bourgogne-Franche-Comté", code: "27" },
  "40": { name: "Nouvelle-Aquitaine", code: "75" },
  "41": { name: "Centre-Val de Loire", code: "24" },
  "42": { name: "Auvergne-Rhône-Alpes", code: "84" },
  "43": { name: "Auvergne-Rhône-Alpes", code: "84" },
  "44": { name: "Pays de la Loire", code: "52" },
  "45": { name: "Centre-Val de Loire", code: "24" },
  "46": { name: "Occitanie", code: "76" },
  "47": { name: "Nouvelle-Aquitaine", code: "75" },
  "48": { name: "Occitanie", code: "76" },
  "49": { name: "Pays de la Loire", code: "52" },
  "50": { name: "Normandie", code: "28" },
  "51": { name: "Grand Est", code: "44" },
  "52": { name: "Grand Est", code: "44" },
  "53": { name: "Pays de la Loire", code: "52" },
  "54": { name: "Grand Est", code: "44" },
  "55": { name: "Grand Est", code: "44" },
  "56": { name: "Bretagne", code: "53" },
  "57": { name: "Grand Est", code: "44" },
  "58": { name: "Bourgogne-Franche-Comté", code: "27" },
  "59": { name: "Hauts-de-France", code: "32" },
  "60": { name: "Hauts-de-France", code: "32" },
  "61": { name: "Normandie", code: "28" },
  "62": { name: "Hauts-de-France", code: "32" },
  "63": { name: "Auvergne-Rhône-Alpes", code: "84" },
  "64": { name: "Nouvelle-Aquitaine", code: "75" },
  "65": { name: "Occitanie", code: "76" },
  "66": { name: "Occitanie", code: "76" },
  "67": { name: "Grand Est", code: "44" },
  "68": { name: "Grand Est", code: "44" },
  "69": { name: "Auvergne-Rhône-Alpes", code: "84" },
  "70": { name: "Bourgogne-Franche-Comté", code: "27" },
  "71": { name: "Bourgogne-Franche-Comté", code: "27" },
  "72": { name: "Pays de la Loire", code: "52" },
  "73": { name: "Auvergne-Rhône-Alpes", code: "84" },
  "74": { name: "Auvergne-Rhône-Alpes", code: "84" },
  "75": { name: "Île-de-France", code: "11" },
  "76": { name: "Normandie", code: "28" },
  "77": { name: "Île-de-France", code: "11" },
  "78": { name: "Île-de-France", code: "11" },
  "79": { name: "Nouvelle-Aquitaine", code: "75" },
  "80": { name: "Hauts-de-France", code: "32" },
  "81": { name: "Occitanie", code: "76" },
  "82": { name: "Occitanie", code: "76" },
  "83": { name: "Provence-Alpes-Côte d'Azur", code: "93" },
  "84": { name: "Provence-Alpes-Côte d'Azur", code: "93" },
  "85": { name: "Pays de la Loire", code: "52" },
  "86": { name: "Nouvelle-Aquitaine", code: "75" },
  "87": { name: "Nouvelle-Aquitaine", code: "75" },
  "88": { name: "Grand Est", code: "44" },
  "89": { name: "Bourgogne-Franche-Comté", code: "27" },
  "90": { name: "Bourgogne-Franche-Comté", code: "27" },
  "91": { name: "Île-de-France", code: "11" },
  "92": { name: "Île-de-France", code: "11" },
  "93": { name: "Île-de-France", code: "11" },
  "94": { name: "Île-de-France", code: "11" },
  "95": { name: "Île-de-France", code: "11" },
  "971": { name: "Guadeloupe", code: "01" },
  "972": { name: "Martinique", code: "02" },
  "973": { name: "Guyane", code: "03" },
  "974": { name: "La Réunion", code: "04" },
  "976": { name: "Mayotte", code: "06" },
};

// Table des noms de départements
export const DEPARTMENT_NAMES = {
  "01": "Ain",
  "02": "Aisne",
  "03": "Allier",
  "04": "Alpes-de-Haute-Provence",
  "05": "Hautes-Alpes",
  "06": "Alpes-Maritimes",
  "07": "Ardèche",
  "08": "Ardennes",
  "09": "Ariège",
  "10": "Aube",
  "11": "Aude",
  "12": "Aveyron",
  "13": "Bouches-du-Rhône",
  "14": "Calvados",
  "15": "Cantal",
  "16": "Charente",
  "17": "Charente-Maritime",
  "18": "Cher",
  "19": "Corrèze",
  "21": "Côte-d'Or",
  "22": "Côtes-d'Armor",
  "23": "Creuse",
  "24": "Dordogne",
  "25": "Doubs",
  "26": "Drôme",
  "27": "Eure",
  "28": "Eure-et-Loir",
  "29": "Finistère",
  "2A": "Corse-du-Sud",
  "2B": "Haute-Corse",
  "30": "Gard",
  "31": "Haute-Garonne",
  "32": "Gers",
  "33": "Gironde",
  "34": "Hérault",
  "35": "Ille-et-Vilaine",
  "36": "Indre",
  "37": "Indre-et-Loire",
  "38": "Isère",
  "39": "Jura",
  "40": "Landes",
  "41": "Loir-et-Cher",
  "42": "Loire",
  "43": "Haute-Loire",
  "44": "Loire-Atlantique",
  "45": "Loiret",
  "46": "Lot",
  "47": "Lot-et-Garonne",
  "48": "Lozère",
  "49": "Maine-et-Loire",
  "50": "Manche",
  "51": "Marne",
  "52": "Haute-Marne",
  "53": "Mayenne",
  "54": "Meurthe-et-Moselle",
  "55": "Meuse",
  "56": "Morbihan",
  "57": "Moselle",
  "58": "Nièvre",
  "59": "Nord",
  "60": "Oise",
  "61": "Orne",
  "62": "Pas-de-Calais",
  "63": "Puy-de-Dôme",
  "64": "Pyrénées-Atlantiques",
  "65": "Hautes-Pyrénées",
  "66": "Pyrénées-Orientales",
  "67": "Bas-Rhin",
  "68": "Haut-Rhin",
  "69": "Rhône",
  "70": "Haute-Saône",
  "71": "Saône-et-Loire",
  "72": "Sarthe",
  "73": "Savoie",
  "74": "Haute-Savoie",
  "75": "Paris",
  "76": "Seine-Maritime",
  "77": "Seine-et-Marne",
  "78": "Yvelines",
  "79": "Deux-Sèvres",
  "80": "Somme",
  "81": "Tarn",
  "82": "Tarn-et-Garonne",
  "83": "Var",
  "84": "Vaucluse",
  "85": "Vendée",
  "86": "Vienne",
  "87": "Haute-Vienne",
  "88": "Vosges",
  "89": "Yonne",
  "90": "Territoire de Belfort",
  "91": "Essonne",
  "92": "Hauts-de-Seine",
  "93": "Seine-Saint-Denis",
  "94": "Val-de-Marne",
  "95": "Val-d'Oise",
  "971": "Guadeloupe",
  "972": "Martinique",
  "973": "Guyane",
  "974": "La Réunion",
  "976": "Mayotte",
};

// Correspondance des codes APE aux libellés
export const APE_CODES = {
  "58.29C": "Édition de logiciels applicatifs",
  "62.01Z": "Programmation informatique",
  "62.02A": "Conseil en systèmes et logiciels informatiques",
  "62.02B": "Tierce maintenance de systèmes et d'applications informatiques",
  "62.03Z": "Gestion d'installations informatiques",
  "62.09Z": "Autres activités informatiques",
  "63.11Z": "Traitement de données, hébergement et activités connexes",
  "63.12Z": "Portails Internet",
  "63.99Z": "Autres services d'information n.c.a.",
  "70.22Z": "Conseil pour les affaires et autres conseils de gestion",
  "72.19Z":
    "Recherche-développement en autres sciences physiques et naturelles",
};

// Correspondance du nombre d'employés aux tranches d'effectifs
export const EMPLOYEE_COUNT_TO_TRANCHE = [
  { min: 0, max: 0, code: "00", label: "0 salarié" },
  { min: 1, max: 2, code: "01", label: "1 ou 2 salariés" },
  { min: 3, max: 5, code: "02", label: "3 à 5 salariés" },
  { min: 6, max: 9, code: "03", label: "6 à 9 salariés" },
  { min: 10, max: 19, code: "11", label: "10 à 19 salariés" },
  { min: 20, max: 49, code: "12", label: "20 à 49 salariés" },
  { min: 50, max: 99, code: "21", label: "50 à 99 salariés" },
  { min: 100, max: 199, code: "22", label: "100 à 199 salariés" },
  { min: 200, max: 249, code: "31", label: "200 à 249 salariés" },
  { min: 250, max: 499, code: "32", label: "250 à 499 salariés" },
  { min: 500, max: 999, code: "41", label: "500 à 999 salariés" },
  { min: 1000, max: 1999, code: "42", label: "1 000 à 1 999 salariés" },
  { min: 2000, max: 4999, code: "51", label: "2 000 à 4 999 salariés" },
  { min: 5000, max: 9999, code: "52", label: "5 000 à 9 999 salariés" },
  {
    min: 10000,
    max: Number.MAX_SAFE_INTEGER,
    code: "53",
    label: "10 000 salariés et plus",
  },
];

// Correspondance des formes juridiques courantes
export const LEGAL_FORMS = {
  // Sociétés commerciales
  "5499": {
    name: "Société à responsabilité limitée (SARL)",
    group: "Société commerciale",
  },
  "5710": {
    name: "Société par actions simplifiée (SAS)",
    group: "Société commerciale",
  },
  "5370": {
    name: "Société Anonyme (SA) à conseil d'administration",
    group: "Société commerciale",
  },
  "5385": {
    name: "Société Anonyme (SA) à directoire",
    group: "Société commerciale",
  },
  "5720": {
    name: "Société par actions simplifiée unipersonnelle (SASU)",
    group: "Société commerciale",
  },
  "5498": { name: "SARL unipersonnelle (EURL)", group: "Société commerciale" },
  "5410": {
    name: "Société en nom collectif (SNC)",
    group: "Société commerciale",
  },
  "5422": {
    name: "Société en commandite simple (SCS)",
    group: "Société commerciale",
  },
  "5426": {
    name: "Société en commandite par actions (SCA)",
    group: "Société commerciale",
  },

  // Sociétés civiles
  "5520": { name: "Société civile", group: "Société civile" },
  "5532": { name: "Société civile immobilière (SCI)", group: "Société civile" },
  "5485": { name: "Société d'exercice libéral (SEL)", group: "Société civile" },
  "5699": { name: "Autre société civile", group: "Société civile" },

  // Entreprises individuelles
  "1000": { name: "Entrepreneur individuel", group: "Entreprise individuelle" },
  "5458": {
    name: "EIRL (Entreprise individuelle à responsabilité limitée)",
    group: "Entreprise individuelle",
  },
  "5813": { name: "Micro-entrepreneur", group: "Entreprise individuelle" },

  // Autres formes
  "6316": { name: "Coopérative", group: "Économie sociale et solidaire" },
  "6318": { name: "SCOP", group: "Économie sociale et solidaire" },
  "9220": { name: "Association", group: "Économie sociale et solidaire" },
  "9210": {
    name: "Association loi 1901",
    group: "Économie sociale et solidaire",
  },
  "9103": { name: "Fondation", group: "Économie sociale et solidaire" },
  "9100": { name: "Syndicat de copropriété", group: "Autre forme juridique" },
};
